springdoc:
  packages-to-scan: com.zaerald.fxratesapi.controller
  paths-to-match: /api/**

server:
  error:
    include-message: always
    include-binding-errors: always

foreign-exchange:
  provider:
    service: exchangeratesapi.io
    # HTTPS is not supported on FREE plan
    url: 'http://api.exchangeratesapi.io/v1'
    accessKey: ${FX_API_KEY:''}
